/**
 * Generate OAuth client credentials for a class roster.
 *
 * Reads a D2L classlist CSV (Name column: "Last, First") and outputs:
 *   1. A .sql file to paste into the Supabase SQL editor
 *   2. A .csv file of plaintext credentials to distribute to students
 *
 * Usage:
 *   npx tsx backend/scripts/provision-clients.ts --classlist classlist.csv
 *   npx tsx backend/scripts/provision-clients.ts --classlist classlist.csv --sql-out clients.sql --out clients.csv
 */

import { createReadStream, writeFileSync } from 'node:fs'
import { createInterface } from 'node:readline'

// ---------------------------------------------------------------------------
// Args
// ---------------------------------------------------------------------------

const args = process.argv.slice(2)

function flag(name: string): string | undefined {
  const i = args.indexOf(name)
  return i !== -1 ? args[i + 1] : undefined
}

const classlistFile = flag('--classlist')
const sqlOut = flag('--sql-out') ?? 'clients.sql'
const csvOut = flag('--out') ?? 'clients-out.csv'

if (!classlistFile) {
  console.error('Usage: provision-clients.ts --classlist <file.csv> [--sql-out clients.sql] [--out clients-out.csv]')
  process.exit(1)
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const SECRET_CHARS = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789'

function generateSecret(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(18))
  return 'mt-' + Array.from(bytes).map((b) => SECRET_CHARS[b % SECRET_CHARS.length]).join('')
}

// "Last, First" → "first-last" (lowercase, hyphens)
function nameToSlug(raw: string): string {
  const comma = raw.indexOf(',')
  if (comma === -1) return raw.trim().toLowerCase().replace(/\s+/g, '-')
  const last = raw.slice(0, comma).trim()
  const first = raw.slice(comma + 1).trim()
  return `${first} ${last}`.toLowerCase().replace(/\s+/g, '-')
}

// "Last, First" → "First Last"
function nameToDisplay(raw: string): string {
  const comma = raw.indexOf(',')
  if (comma === -1) return raw.trim()
  const last = raw.slice(0, comma).trim()
  const first = raw.slice(comma + 1).trim()
  return `${first} ${last}`
}

// Escape single quotes for SQL string literals
function sqlStr(s: string): string {
  return s.replace(/'/g, "''")
}

async function parseClasslist(path: string): Promise<{ name: string; email: string }[]> {
  const students: { name: string; email: string }[] = []
  const rl = createInterface({ input: createReadStream(path), crlfDelay: Infinity })

  let headers: string[] = []
  let first = true

  for await (const line of rl) {
    if (first) {
      headers = line.split(',').map((h) => h.replace(/^"|"$/g, '').trim())
      first = false
      continue
    }
    if (!line.trim()) continue

    // Simple CSV parse — handles quoted fields with commas (like "Last, First")
    const fields: string[] = []
    let inQuote = false
    let cur = ''
    for (const ch of line) {
      if (ch === '"') { inQuote = !inQuote; continue }
      if (ch === ',' && !inQuote) { fields.push(cur); cur = ''; continue }
      cur += ch
    }
    fields.push(cur)

    const row: Record<string, string> = {}
    headers.forEach((h, i) => { row[h] = (fields[i] ?? '').trim() })

    if (row['Role'] !== 'Student') continue

    const name = row['Name']?.trim()
    const email = row['Email']?.trim()
    if (name) students.push({ name, email: email ?? '' })
  }

  return students
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const students = await parseClasslist(classlistFile)
console.log(`Parsed ${students.length} students from ${classlistFile}`)

const rows: { clientId: string; clientSecret: string; displayName: string; email: string }[] = []

for (const { name, email } of students) {
  const clientId = `ics342-${nameToSlug(name)}`
  const clientSecret = generateSecret()
  const displayName = nameToDisplay(name)
  rows.push({ clientId, clientSecret, displayName, email })
}

// ---------------------------------------------------------------------------
// SQL output
// ---------------------------------------------------------------------------

const valueLines = rows
  .map((r) => `  ('${sqlStr(r.clientId)}', crypt('${sqlStr(r.clientSecret)}', gen_salt('bf', 12)), '${sqlStr(r.displayName)}')`)
  .join(',\n')

const sql = `-- Generated by provision-clients.ts — ${new Date().toISOString()}
-- Paste into Supabase SQL Editor and run.
-- The plaintext secrets are in ${csvOut} — distribute to students, then delete that file.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO public.oauth_clients (client_id, client_secret_hash, description)
VALUES
${valueLines}
ON CONFLICT (client_id) DO UPDATE SET
  client_secret_hash = EXCLUDED.client_secret_hash,
  description        = EXCLUDED.description;
`

writeFileSync(sqlOut, sql, 'utf8')
console.log(`SQL written to: ${sqlOut}`)

// ---------------------------------------------------------------------------
// CSV output
// ---------------------------------------------------------------------------

const csv =
  'name,email,clientId,clientSecret\n' +
  rows.map((r) => `${r.displayName},${r.email},${r.clientId},${r.clientSecret}`).join('\n') +
  '\n'

writeFileSync(csvOut, csv, 'utf8')
console.log(`Plaintext credentials written to: ${csvOut}`)
console.log('Distribute this CSV to students, then delete it.')
