-- Follows: user-to-user relationships
CREATE TABLE IF NOT EXISTS public.follows (
  id           integer generated by default as identity primary key,
  follower_id  UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  following_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(follower_id, following_id)
);

CREATE INDEX IF NOT EXISTS idx_follows_follower  ON public.follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_following ON public.follows(following_id);

ALTER TABLE public.follows
  ADD CONSTRAINT chk_no_self_follow
  CHECK (follower_id != following_id);

-- Activity feed: records notable user actions for the social feed
CREATE TABLE IF NOT EXISTS public.activity_feed (
  id            integer generated by default as identity primary key,
  user_id       UUID    NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  activity_type text NOT NULL,
  media_id      INTEGER     REFERENCES public.media(id) ON DELETE CASCADE,
  rating        INTEGER,
  review_text   text,
  status        text,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_activity_user    ON public.activity_feed(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_created ON public.activity_feed(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_type    ON public.activity_feed(activity_type);

ALTER TABLE public.activity_feed
  ADD CONSTRAINT chk_activity_type
  CHECK (activity_type IN ('review', 'added', 'finished', 'started'));
