-- User library: tracks a user's relationship with a media item
CREATE TABLE IF NOT EXISTS public.user_media (
  id          integer generated by default as identity primary key,
  user_id     UUID    NOT NULL REFERENCES public.users(id)  ON DELETE CASCADE,
  media_id    INTEGER NOT NULL REFERENCES public.media(id)  ON DELETE CASCADE,
  status      text NOT NULL,
  added_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  started_at  TIMESTAMP WITH TIME ZONE,
  finished_at TIMESTAMP WITH TIME ZONE,
  updated_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, media_id)
);

CREATE INDEX IF NOT EXISTS idx_user_media_user_status ON public.user_media(user_id, status);
CREATE INDEX IF NOT EXISTS idx_user_media_media       ON public.user_media(media_id);
CREATE INDEX IF NOT EXISTS idx_user_media_added       ON public.user_media(added_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_media_finished    ON public.user_media(finished_at DESC)
  WHERE finished_at IS NOT NULL;

ALTER TABLE public.user_media
  ADD CONSTRAINT chk_status
  CHECK (status IN ('want_to', 'reading', 'in_progress', 'finished'));
