-- Want-to priorities: ordered priority list for a user's want-to items
CREATE TABLE IF NOT EXISTS public.want_to_priorities (
  id                    integer generated by default as identity primary key,
  user_id               UUID    NOT NULL REFERENCES public.users(id)       ON DELETE CASCADE,
  user_media_id         INTEGER NOT NULL REFERENCES public.user_media(id)  ON DELETE CASCADE,
  priority              INTEGER NOT NULL,
  order_index           INTEGER NOT NULL,
  estimated_time_hours  INTEGER,
  notes                 text CHECK (char_length(notes) <= 200),
  created_at            TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at            TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, user_media_id)
);

CREATE INDEX IF NOT EXISTS idx_priorities_user ON public.want_to_priorities(user_id, order_index);

ALTER TABLE public.want_to_priorities
  ADD CONSTRAINT chk_priority_level
  CHECK (priority IN (1, 2, 3));

-- Reading / watch goals per year
CREATE TABLE IF NOT EXISTS public.reading_goals (
  id           integer generated by default as identity primary key,
  user_id      UUID    NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  year         INTEGER NOT NULL,
  target_count INTEGER NOT NULL,
  media_type   text,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, year, media_type)
);

ALTER TABLE public.reading_goals
  ADD CONSTRAINT chk_media_type_null_or_valid
  CHECK (media_type IS NULL OR media_type IN ('book', 'movie'));

ALTER TABLE public.reading_goals
  ADD CONSTRAINT chk_target_positive
  CHECK (target_count > 0);

-- Milestone achievements for a goal (25 / 50 / 75 / 100 %)
CREATE TABLE IF NOT EXISTS public.goal_achievements (
  id          integer generated by default as identity primary key,
  goal_id     INTEGER NOT NULL REFERENCES public.reading_goals(id) ON DELETE CASCADE,
  milestone   INTEGER NOT NULL,
  unlocked_at TIMESTAMP WITH TIME ZONE,
  UNIQUE(goal_id, milestone)
);

ALTER TABLE public.goal_achievements
  ADD CONSTRAINT chk_milestone
  CHECK (milestone IN (25, 50, 75, 100));

-- Quotes saved by users from books or movies
CREATE TABLE IF NOT EXISTS public.quotes (
  id                integer generated by default as identity primary key,
  user_id           UUID    NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  media_id          INTEGER NOT NULL REFERENCES public.media(id) ON DELETE CASCADE,
  quote_text        text NOT NULL,
  page_number       INTEGER,
  timestamp_seconds INTEGER,
  is_public         BOOLEAN DEFAULT TRUE,
  like_count        INTEGER DEFAULT 0,
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_quotes_user   ON public.quotes(user_id);
CREATE INDEX IF NOT EXISTS idx_quotes_media  ON public.quotes(media_id);
CREATE INDEX IF NOT EXISTS idx_quotes_public ON public.quotes(is_public, created_at DESC)
  WHERE is_public = TRUE;
CREATE INDEX IF NOT EXISTS idx_quotes_likes  ON public.quotes(like_count DESC)
  WHERE is_public = TRUE;

ALTER TABLE public.quotes
  ADD CONSTRAINT chk_quote_length
  CHECK (char_length(quote_text) <= 500);

-- Likes on quotes
CREATE TABLE IF NOT EXISTS public.quote_likes (
  id         integer generated by default as identity primary key,
  quote_id   INTEGER NOT NULL REFERENCES public.quotes(id) ON DELETE CASCADE,
  user_id    UUID    NOT NULL REFERENCES public.users(id)  ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(quote_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_quote_likes_quote ON public.quote_likes(quote_id);
CREATE INDEX IF NOT EXISTS idx_quote_likes_user  ON public.quote_likes(user_id);
