-- Media table: pre-seeded books (~300) and movies (~300)
CREATE TABLE IF NOT EXISTS public.media (
  id               integer generated by default as identity primary key,
  media_type       text             NOT NULL,
  title            text             NOT NULL,
  author           text,
  director         text,
  cover_url        text,
  description      TEXT,
  published_year   INTEGER,
  page_count       INTEGER,
  runtime_minutes  INTEGER,
  genres           TEXT[]           DEFAULT '{}',
  isbn             text,
  language         text             DEFAULT 'en',

  -- Aggregate ratings (kept up-to-date by trigger)
  average_rating   DECIMAL(3,2)     DEFAULT 0,
  rating_count     INTEGER          DEFAULT 0,
  review_count     INTEGER          DEFAULT 0,

  seeded_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_media_type         ON public.media(media_type);
CREATE INDEX IF NOT EXISTS idx_media_title_trgm   ON public.media USING gin(title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_media_author_trgm  ON public.media USING gin(author gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_media_director_trgm ON public.media USING gin(director gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_media_genres       ON public.media USING gin(genres);
CREATE INDEX IF NOT EXISTS idx_media_year         ON public.media(published_year);
CREATE INDEX IF NOT EXISTS idx_media_rating       ON public.media(average_rating DESC);

ALTER TABLE public.media
  ADD CONSTRAINT chk_media_type
  CHECK (media_type IN ('book', 'movie'));

ALTER TABLE public.media
  ADD CONSTRAINT chk_rating_range
  CHECK (average_rating >= 0 AND average_rating <= 5);
