-- Reviews: one per user per media item
CREATE TABLE IF NOT EXISTS public.reviews (
  id          integer generated by default as identity primary key,
  user_id     UUID    NOT NULL REFERENCES public.users(id)  ON DELETE CASCADE,
  media_id    INTEGER NOT NULL REFERENCES public.media(id)  ON DELETE CASCADE,
  rating      INTEGER NOT NULL,
  review_text text,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, media_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_media   ON public.reviews(media_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user    ON public.reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_rating  ON public.reviews(rating DESC);
CREATE INDEX IF NOT EXISTS idx_reviews_created ON public.reviews(created_at DESC);

ALTER TABLE public.reviews
  ADD CONSTRAINT chk_rating
  CHECK (rating >= 1 AND rating <= 5);

ALTER TABLE public.reviews
  ADD CONSTRAINT chk_review_length
  CHECK (char_length(review_text) <= 500);
